name: Sync Aneurysm_Detection from Upstream (PR)

on:
  schedule:
    - cron: '0 19 * * *'   # daily at 19:00 UTC (note: cron won't run on forks)
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/Aneurysm_Detection_sync.yml'  # lets you test on commit

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      UPSTREAM_REPO: https://github.com/2ai-lab/Aneurysm_Detection.git
      UPSTREAM_BRANCH: main      # change if upstream uses a different default
      BASE_BRANCH: main          # change if your repo's default branch differs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream and fetch
        run: |
          git remote add upstream "${UPSTREAM_REPO}"
          git fetch upstream "${UPSTREAM_BRANCH}"

      - name: Merge upstream into a new sync branch
        run: |
          BRANCH="sync/upstream-$(date +%Y%m%d-%H%M%S)"
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV
          git checkout "${BASE_BRANCH}"
          git checkout -B "$BRANCH"
          set -e
          git merge --no-edit "upstream/${UPSTREAM_BRANCH}" || {
            echo "::error::Automatic merge failed. Resolve conflicts manually."
            exit 1
          }

      - name: Open pull request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Sync from upstream 2ai-lab/Aneurysm_Detection"
          title: "Sync: upstream → ${UPSTREAM_BRANCH} into ${BASE_BRANCH}"
          body: |
            Automated sync from **2ai-lab/Aneurysm_Detection**.
            - Base: `${{ env.BASE_BRANCH }}`
            - Upstream branch: `${{ env.UPSTREAM_BRANCH }}`
            - Created by GitHub Actions.
          branch: ${{ env.BRANCH }}
          base: ${{ env.BASE_BRANCH }}
          labels: auto-sync
          draft: false
