name: Sync Aneurysm_Detection from Upstream (Push)

on:
  schedule:
    - cron: '0 19 * * *'   # daily at 19:00 UTC (⚠️ cron won’t fire on forks)
  workflow_dispatch:        # run manually from Actions tab
  push:                     # test by committing this file
    paths:
      - '.github/workflows/Aneurysm_Detection_sync.yml'

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      UPSTREAM_REPO: https://github.com/2ai-lab/Aneurysm_Detection.git
      UPSTREAM_BRANCH: main
      BASE_BRANCH: main
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream and fetch
        run: |
          git remote add upstream "${UPSTREAM_REPO}"
          git fetch upstream "${UPSTREAM_BRANCH}"

      - name: Merge upstream and push
        run: |
          git checkout "${BASE_BRANCH}"
          git merge --no-edit "upstream/${UPSTREAM_BRANCH}" || {
            echo "::error::Automatic merge failed. Resolve conflicts manually."
            exit 1
          }
          git push origin "${BASE_BRANCH}"
